// AUTO-GENERATED by scripts/sync_opencv_imgproc_cases.py
// Upstream OpenCV commit: opencv-4.13.0
// Source: modules/imgproc/test/test_color.cpp
// This file intentionally stores exact upstream TEST blocks.
// Do not edit manually; re-run sync script.

// BEGIN ImgProc_cvtColor_InvalidNumOfChannels.regression_25971 (PASS_NOW)
TEST(ImgProc_cvtColor_InvalidNumOfChannels, regression_25971)
{
    try {
        cv::Mat src = cv::Mat::zeros(100, 100, CV_8UC1);
        cv::Mat dst;
        EXPECT_THROW(cv::cvtColor(src, dst, COLOR_RGB2GRAY), cv::Exception);
    }catch(const cv::Exception& e) {
        EXPECT_EQ(e.code, cv::Error::BadNumChannels);
    }catch(...) {
        FAIL() << "Unexpected exception is happened.";
    }
}
// END ImgProc_cvtColor_InvalidNumOfChannels.regression_25971

