// AUTO-GENERATED by scripts/sync_opencv_imgproc_cases.py
// Upstream OpenCV commit: opencv-4.13.0
// Source: modules/imgproc/test/test_contours.cpp
// This file intentionally stores exact upstream TEST blocks.
// Do not edit manually; re-run sync script.

// BEGIN Imgproc_FindContours.border (PASS_NOW)
TEST(Imgproc_FindContours, border)
{
    Mat img;
    cv::copyMakeBorder(Mat::zeros(8, 10, CV_8U), img, 1, 1, 1, 1, BORDER_CONSTANT, Scalar(1));

    std::vector<std::vector<cv::Point> > contours;
    findContours(img, contours, RETR_LIST, CHAIN_APPROX_NONE);

    Mat img_draw_contours = Mat::zeros(img.size(), CV_8U);
    for (size_t cpt = 0; cpt < contours.size(); cpt++)
    {
      drawContours(img_draw_contours, contours, static_cast<int>(cpt), cv::Scalar(1));
    }

    ASSERT_EQ(0, cvtest::norm(img, img_draw_contours, NORM_INF));
}
// END Imgproc_FindContours.border

