// AUTO-GENERATED by scripts/sync_opencv_imgproc_cases.py
// Upstream OpenCV commit: opencv-4.13.0
// Source: modules/imgproc/test/test_canny.cpp
// This file intentionally stores exact upstream TEST blocks.
// Do not edit manually; re-run sync script.

// BEGIN Canny_Modes.accuracy (PASS_NOW)
TEST_P(Canny_Modes, accuracy)
{
    const int aperture = get<0>(GetParam());
    const bool trueGradient = get<1>(GetParam());
    const double range = aperture == 3 ? 300. : 1000.;
    RNG & rng = TS::ptr()->get_rng();

    for (int ITER = 0; ITER < 20; ++ITER)
    {
        SCOPED_TRACE(cv::format("iteration %d", ITER));

        const std::string fname = cvtest::findDataFile("shared/fruits.png");
        const Mat original = cv::imread(fname, IMREAD_GRAYSCALE);

        const double thresh1 = rng.uniform(0., range);
        const double thresh2 = rng.uniform(0., range * 0.3);
        const Size sz(rng.uniform(127, 800), rng.uniform(127, 600));
        const Size osz = original.size();

        // preparation
        Mat img;
        if (sz.width >= osz.width || sz.height >= osz.height)
        {
            // larger image -> scale
            resize(original, img, sz, 0, 0, INTER_LINEAR_EXACT);
        }
        else
        {
            // smaller image -> crop
            Point origin(rng.uniform(0, osz.width - sz.width), rng.uniform(0, osz.height - sz.height));
            Rect roi(origin, sz);
            original(roi).copyTo(img);
        }
        GaussianBlur(img, img, Size(5, 5), 0);

        // regular function
        Mat result;
        {
            cv::Canny(img, result, thresh1, thresh2, aperture, trueGradient);
        }

        // custom derivatives
        Mat customResult;
        {
            Mat dxkernel = cvtest::calcSobelKernel2D(1, 0, aperture, 0);
            Mat dykernel = cvtest::calcSobelKernel2D(0, 1, aperture, 0);
            Point anchor(aperture / 2, aperture / 2);
            cv::Mat dx, dy;
            cvtest::filter2D(img, dx, CV_16S, dxkernel, anchor, 0, BORDER_REPLICATE);
            cvtest::filter2D(img, dy, CV_16S, dykernel, anchor, 0, BORDER_REPLICATE);
            cv::Canny(dx, dy, customResult, thresh1, thresh2, trueGradient);
        }

        Mat reference;
        Canny_reference(img, reference, thresh1, thresh2, aperture, trueGradient);

        EXPECT_MAT_NEAR(result, reference, 0);
        EXPECT_MAT_NEAR(customResult, reference, 0);
    }
}
// END Canny_Modes.accuracy

