// AUTO-GENERATED by scripts/sync_opencv_imgproc_cases.py
// Upstream OpenCV commit: opencv-4.13.0
// Source: modules/imgproc/test/test_thresh.cpp
// This file intentionally stores exact upstream TEST blocks.
// Do not edit manually; re-run sync script.

// BEGIN Imgproc_Threshold.threshold_dryrun (PASS_NOW)
TEST(Imgproc_Threshold, threshold_dryrun)
{
    Size sz(16, 16);
    Mat input_original(sz, CV_8U, Scalar::all(2));
    Mat input = input_original.clone();
    std::vector<int> threshTypes = {THRESH_BINARY, THRESH_BINARY_INV, THRESH_TRUNC, THRESH_TOZERO, THRESH_TOZERO_INV};
    std::vector<int> threshFlags = {0, THRESH_OTSU, THRESH_TRIANGLE};
    for(int threshType : threshTypes)
    {
        for(int threshFlag : threshFlags)
        {
            const int _threshType = threshType | threshFlag | THRESH_DRYRUN;
            cv::threshold(input, input, 2.0, 0.0, _threshType);
            EXPECT_MAT_NEAR(input, input_original, 0);
        }
    }
}
// END Imgproc_Threshold.threshold_dryrun

