// AUTO-GENERATED by scripts/sync_opencv_imgproc_cases.py
// Upstream OpenCV commit: d719c6d
// Source: modules/imgproc/test/test_imgwarp.cpp
// This file intentionally stores exact upstream TEST blocks.
// Do not edit manually; re-run sync script.

// BEGIN Resize.nearest_regression_15075 (PASS_NOW)
TEST(Resize, nearest_regression_15075)
{
    const int C = 5;
    const int i1 = 5, j1 = 5;
    Size src_size(12, 12);
    Size dst_size(11, 11);

    cv::Mat src = cv::Mat::zeros(src_size, CV_8UC(C)), dst;
    for (int j = 0; j < C; j++)
        src.col(i1).row(j1).data[j] = 1;

    cv::resize(src, dst, dst_size, 0, 0, INTER_NEAREST);
    EXPECT_EQ(C, cvtest::norm(dst, NORM_L1)) << src.size;
}
// END Resize.nearest_regression_15075

