// AUTO-GENERATED by scripts/sync_opencv_core_channel_cases.py
// Upstream OpenCV commit: d719c6d
// Source: modules/core/test/test_arithm.cpp
// This file intentionally stores exact upstream TEST blocks.
// Do not edit manually; re-run sync script.

// BEGIN Subtract.scalarc1_matc3
TEST(Subtract, scalarc1_matc3)
{
    int scalar = 255;
    cv::Mat srcImage(5, 5, CV_8UC3, cv::Scalar::all(5)), destImage;
    cv::subtract(scalar, srcImage, destImage);

    ASSERT_EQ(0, cv::norm(cv::Mat(5, 5, CV_8UC3, cv::Scalar::all(250)), destImage, cv::NORM_INF));
}
// END Subtract.scalarc1_matc3

// BEGIN Subtract.scalarc4_matc4
TEST(Subtract, scalarc4_matc4)
{
    cv::Scalar sc(255, 255, 255, 255);
    cv::Mat srcImage(5, 5, CV_8UC4, cv::Scalar::all(5)), destImage;
    cv::subtract(sc, srcImage, destImage);

    ASSERT_EQ(0, cv::norm(cv::Mat(5, 5, CV_8UC4, cv::Scalar::all(250)), destImage, cv::NORM_INF));
}
// END Subtract.scalarc4_matc4

// BEGIN Compare.empty
TEST(Compare, empty)
{
    cv::Mat temp, dst1, dst2;
    EXPECT_NO_THROW(cv::compare(temp, temp, dst1, cv::CMP_EQ));
    EXPECT_TRUE(dst1.empty());
    EXPECT_THROW(dst2 = temp > 5, cv::Exception);
}
// END Compare.empty

// BEGIN Compare.regression_8999
TEST(Compare, regression_8999)
{
    Mat_<double> A(4,1); A << 1, 3, 2, 4;
    Mat_<double> B(1,1); B << 2;
    Mat C;
    EXPECT_THROW(cv::compare(A, B, C, CMP_LT), cv::Exception);
}
// END Compare.regression_8999

// BEGIN Compare.regression_16F_do_not_crash
TEST(Compare, regression_16F_do_not_crash)
{
    cv::Mat mat1(2, 2, CV_16F, cv::Scalar(1));
    cv::Mat mat2(2, 2, CV_16F, cv::Scalar(2));
    cv::Mat dst;
    EXPECT_THROW(cv::compare(mat1, mat2, dst, cv::CMP_EQ), cv::Exception);
}
// END Compare.regression_16F_do_not_crash

// BEGIN Core_LUT.accuracy
TEST_P(Core_LUT, accuracy)
{
    int idx_type = get<0>(GetParam());
    int value_type = get<1>(GetParam());

    ASSERT_TRUE((idx_type == CV_8U) || (idx_type == CV_8S) || (idx_type == CV_16U ) || (idx_type == CV_16S));
    const int tableSize = ((idx_type == CV_8U) || (idx_type == CV_8S)) ? 256: 65536;

    cv::Mat input(117, 113, CV_MAKE_TYPE(idx_type, 1));
    randu(input, getMinVal(idx_type), getMaxVal(idx_type));

    cv::Mat table(1, tableSize, CV_MAKE_TYPE(value_type, 1));
    randu(table, getMinVal(value_type), getMaxVal(value_type));

    cv::Mat output;
    ASSERT_NO_THROW(cv::LUT(input, table, output));
    ASSERT_FALSE(output.empty());

    cv::Mat gt = reference(input, table);
    ASSERT_FALSE(gt.empty());

    ASSERT_EQ(0, cv::norm(output, gt, cv::NORM_INF));
}
// END Core_LUT.accuracy

// BEGIN Core_LUT.accuracy_multi
TEST_P(Core_LUT, accuracy_multi)
{
    int idx_type = get<0>(GetParam());
    int value_type = get<1>(GetParam());

    ASSERT_TRUE((idx_type == CV_8U) || (idx_type == CV_8S) || (idx_type == CV_16U) || (idx_type == CV_16S));
    const int tableSize = ((idx_type == CV_8U) || (idx_type == CV_8S) ) ? 256: 65536;

    cv::Mat input(117, 113, CV_MAKE_TYPE(idx_type, 3));
    randu(input, getMinVal(idx_type), getMaxVal(idx_type));

    cv::Mat table(1, tableSize, CV_MAKE_TYPE(value_type, 1));
    randu(table, getMinVal(value_type), getMaxVal(value_type));

    cv::Mat output;
    ASSERT_NO_THROW(cv::LUT(input, table, output));
    ASSERT_FALSE(output.empty());

    cv::Mat gt = reference<3>(input, table);
    ASSERT_FALSE(gt.empty());

    ASSERT_EQ(0, cv::norm(output, gt, cv::NORM_INF));
}
// END Core_LUT.accuracy_multi

// BEGIN Core_LUT.accuracy_multi2
TEST_P(Core_LUT, accuracy_multi2)
{
    int idx_type = get<0>(GetParam());
    int value_type = get<1>(GetParam());

    ASSERT_TRUE((idx_type == CV_8U) || (idx_type == CV_8S) || (idx_type == CV_16U) || (idx_type == CV_16S));
    const int tableSize = ((idx_type == CV_8U) || (idx_type == CV_8S)) ? 256: 65536;

    cv::Mat input(117, 113, CV_MAKE_TYPE(idx_type, 3));
    randu(input, getMinVal(idx_type), getMaxVal(idx_type));

    cv::Mat table(1, tableSize, CV_MAKE_TYPE(value_type, 3));
    randu(table, getMinVal(value_type), getMaxVal(value_type));

    cv::Mat output;
    ASSERT_NO_THROW(cv::LUT(input, table, output));
    ASSERT_FALSE(output.empty());

    cv::Mat gt = reference<3, true>(input, table);
    ASSERT_FALSE(gt.empty());

    ASSERT_EQ(0, cv::norm(output, gt, cv::NORM_INF));
}
// END Core_LUT.accuracy_multi2
