#!/usr/bin/env python3
"""Sync the vendored OpenCV Universal Intrinsics whitelist."""

from __future__ import annotations

import argparse
import filecmp
import re
import shutil
import subprocess
from pathlib import Path


DEFAULT_OPENCV_ROOT = Path("/Users/zmu/work/my_project/ocvh/opencv")
REPO_ROOT = Path(__file__).resolve().parents[1]
VENDOR_ROOT = REPO_ROOT / "include" / "cvh" / "3rdparty" / "opencv_intrin"
UPSTREAM_MD = VENDOR_ROOT / "UPSTREAM.md"

WHITELIST = {
    "modules/core/include/opencv2/core/hal/intrin.hpp": "opencv2/core/hal/intrin.hpp",
    "modules/core/include/opencv2/core/hal/intrin_cpp.hpp": "opencv2/core/hal/intrin_cpp.hpp",
    "modules/core/include/opencv2/core/hal/intrin_forward.hpp": "opencv2/core/hal/intrin_forward.hpp",
    "modules/core/include/opencv2/core/hal/intrin_math.hpp": "opencv2/core/hal/intrin_math.hpp",
    "modules/core/include/opencv2/core/hal/intrin_neon.hpp": "opencv2/core/hal/intrin_neon.hpp",
    "modules/core/include/opencv2/core/hal/intrin_sse_em.hpp": "opencv2/core/hal/intrin_sse_em.hpp",
    "modules/core/include/opencv2/core/hal/intrin_sse.hpp": "opencv2/core/hal/intrin_sse.hpp",
    "modules/core/include/opencv2/core/hal/intrin_avx.hpp": "opencv2/core/hal/intrin_avx.hpp",
    "modules/core/include/opencv2/core/hal/intrin_avx512.hpp": "opencv2/core/hal/intrin_avx512.hpp",
    "modules/core/include/opencv2/core/hal/simd_utils.impl.hpp": "opencv2/core/hal/simd_utils.impl.hpp",
    "LICENSE": "LICENSE.opencv",
}

LOCAL_SHIMS = (
    "opencv2/core/cvdef.h",
    "opencv2/core/saturate.hpp",
    "opencv2/core/utility.hpp",
)

EXPECTED_VENDOR_FILES = set(WHITELIST.values()) | set(LOCAL_SHIMS) | {"UPSTREAM.md"}


def git_value(opencv_root: Path, *args: str) -> str:
    return subprocess.check_output(
        ["git", "-C", str(opencv_root), *args],
        text=True,
        stderr=subprocess.DEVNULL,
    ).strip()


def opencv_version_header(opencv_root: Path) -> str:
    version_header = opencv_root / "modules" / "core" / "include" / "opencv2" / "core" / "version.hpp"
    text = version_header.read_text(encoding="utf-8")

    def define_value(name: str) -> str:
        match = re.search(rf"^\s*#define\s+{name}\s+(.+?)\s*$", text, re.MULTILINE)
        if not match:
            raise SystemExit(f"Missing {name} in {version_header}")
        value = match.group(1).split("//", 1)[0].strip()
        if value.startswith('"') and value.endswith('"'):
            value = value[1:-1]
        return value

    major = define_value("CV_VERSION_MAJOR")
    minor = define_value("CV_VERSION_MINOR")
    revision = define_value("CV_VERSION_REVISION")
    status = define_value("CV_VERSION_STATUS")
    return f"{major}.{minor}.{revision}{status}"


def expected_upstream_markdown(opencv_root: Path, describe: str, head: str) -> str:
    imported_files = "\n".join(f"{source}" for source in WHITELIST.keys())
    shims = "\n".join(LOCAL_SHIMS)
    version = opencv_version_header(opencv_root)
    return f"""# OpenCV Universal Intrinsics Upstream

## Source

- Repository: `{opencv_root}`
- Version describe: `{describe}`
- Commit: `{head}`
- OpenCV version header: `{version}`

## Imported Files

The import intentionally uses a small whitelist. It does not vendor the full OpenCV HAL or full OpenCV core.

Original OpenCV files copied without manual edits:

```text
{imported_files}
```

Local compatibility shims:

```text
{shims}
```

## Local Policy

- Do not import `cv_hal_*`, `CALL_HAL`, `custom_hal.hpp`, or OpenCV module dispatch machinery in this vendor tree.
- Do not add an OpenCV binary or build-time dependency.
- Keep direct uses of OpenCV UI inside `include/cvh/**` implementation headers; do not expose `cv::v_*` types as `cvh` public API.
- Use `scripts/sync_opencv_intrin.py --check` before committing changes to this vendor tree.
- Run the P5.4 correctness and benchmark gates before updating the recorded upstream commit.

## Maintenance Contract

- The whitelist above is the only OpenCV source surface allowed in `include/cvh/3rdparty/opencv_intrin`.
- `UPSTREAM.md` is generated by `scripts/sync_opencv_intrin.py` and must match the local OpenCV source tree used for sync.
- Local shims are maintained by `cvh`; they must stay minimal and only provide declarations required by the imported Universal Intrinsics headers.

## Current Scope

`cvh::headers` enables these OpenCV UI headers by default for benchmark-gated header-only fast paths. `cvh::headers_fast` inherits them and only adds extra platform fast-profile toggles. Current accepted paths are:

- `CV_8UC3` `BGR2GRAY` / `RGB2GRAY`
- `CV_8UC1` exact 2x `INTER_LINEAR` resize

Platform UI headers currently imported by policy:

- Scalar / portable fallback: `intrin_cpp.hpp`
- ARM: `intrin_neon.hpp`
- x86: `intrin_sse_em.hpp`, `intrin_sse.hpp`, `intrin_avx.hpp`, `intrin_avx512.hpp`

x86 AVX-family paths may be enabled from compiler feature macros by the local `cvdef.h` shim. SSE headers/macros exist only as x86 OpenCV UI/AVX prerequisites. RVV is intentionally deferred and is not vendored or enabled because the current NEON/AVX porting target is fixed-lane OpenCV UI code; scalable RVV needs a separate design and remains a future TODO.
"""


def vendor_file_set() -> set[str]:
    if not VENDOR_ROOT.exists():
        return set()
    return {
        str(path.relative_to(VENDOR_ROOT))
        for path in VENDOR_ROOT.rglob("*")
        if path.is_file()
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--opencv-root",
        type=Path,
        default=DEFAULT_OPENCV_ROOT,
        help="Path to the local OpenCV source tree",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify vendored files, metadata, and whitelist boundaries",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    opencv_root = args.opencv_root.resolve()
    if not (opencv_root / "modules" / "core" / "include" / "opencv2" / "core" / "hal" / "intrin.hpp").exists():
        raise SystemExit(f"OpenCV source tree not found: {opencv_root}")

    head = git_value(opencv_root, "rev-parse", "HEAD")
    describe = git_value(opencv_root, "describe", "--tags", "--always", "--dirty")
    expected_upstream = expected_upstream_markdown(opencv_root, describe, head)

    changed = []
    missing = []
    extra = []
    for source_rel, dest_rel in WHITELIST.items():
        source = opencv_root / source_rel
        dest = VENDOR_ROOT / dest_rel
        if not source.exists():
            raise SystemExit(f"Missing upstream file: {source}")
        if args.check:
            if not dest.exists():
                missing.append(str(dest.relative_to(REPO_ROOT)))
            elif not filecmp.cmp(source, dest, shallow=False):
                changed.append(str(dest.relative_to(REPO_ROOT)))
        else:
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, dest)
            changed.append(str(dest.relative_to(REPO_ROOT)))

    if args.check:
        for shim in LOCAL_SHIMS:
            if not (VENDOR_ROOT / shim).exists():
                missing.append(str((VENDOR_ROOT / shim).relative_to(REPO_ROOT)))
        if not UPSTREAM_MD.exists():
            missing.append(str(UPSTREAM_MD.relative_to(REPO_ROOT)))
        elif UPSTREAM_MD.read_text(encoding="utf-8") != expected_upstream:
            changed.append(str(UPSTREAM_MD.relative_to(REPO_ROOT)))

        actual_vendor_files = vendor_file_set()
        for path in sorted(actual_vendor_files - EXPECTED_VENDOR_FILES):
            extra.append(str((VENDOR_ROOT / path).relative_to(REPO_ROOT)))

        if missing or changed:
            for path in missing:
                print(f"[opencv-intrin] missing: {path}")
            for path in changed:
                print(f"[opencv-intrin] out-of-sync: {path}")
            for path in extra:
                print(f"[opencv-intrin] unexpected: {path}")
            return 1
        if extra:
            for path in extra:
                print(f"[opencv-intrin] unexpected: {path}")
            return 1
        print(f"[opencv-intrin] OK: {describe} {head}")
        return 0

    for shim in LOCAL_SHIMS:
        if not (VENDOR_ROOT / shim).exists():
            raise SystemExit(f"Missing local shim: {VENDOR_ROOT / shim}")
    UPSTREAM_MD.write_text(expected_upstream, encoding="utf-8")
    changed.append(str(UPSTREAM_MD.relative_to(REPO_ROOT)))

    for path in changed:
        print(f"[opencv-intrin] synced: {path}")
    print(f"[opencv-intrin] upstream: {describe} {head}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
